---
# vim:ff=unix ts=2 sw=2 ai expandtab
-
  hosts: dev_machine

  sudo: False

  vars_files:
    - "../default_variables.yaml"

  tasks:
    - name: "Installing jhbuild dependencies - this may take a very long time"
      shell: executable=/bin/bash echo -e "y\n" | ~/.local/bin/jhbuild sysdeps --install

    - name: "Installing auth key"
      template: src=../templates/.jhbuildrc-auth.j2 dest=~/.jhbuildrc-auth
