---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: "Ensuring that git is installed"
  apt: name=git

- name: "Creating checkout directory"
  file: path=~/checkout state=directory mode=755

- name: "Cloning jhbuild"
  git: repo=git://git.gnome.org/jhbuild
       dest=~/checkout/jhbuild

- name: "Installing jhbuild - autogen"
  shell: cd ~/checkout/jhbuild && ./autogen.sh

- name: "Installing jhbuild - make"
  shell: cd ~/checkout/jhbuild && make 

- name: "Installing jhbuild - make install"
  shell: cd ~/checkout/jhbuild && make install

- name: "Creating glib schemas dir"
  file: path=~/install/share/glib-2.0/schemas state=directory mode=755
