---
# vim:ff=unix ts=2 sw=2 ai expandtab
-
  hosts: dev_machine

  sudo: False

  vars_files:
    - "../default_variables.yaml"

  tasks:
    - name: "Ensuring that git is installed"
      apt: name=git update_cache=true cache_valid_time=259200

    - name: "Creating checkout directory"
      file: path=~/checkout state=directory mode=755

    - name: "Cloning jhbuild"
      git: repo=git://git.gnome.org/jhbuild
           dest=~/checkout/jhbuild

    - name: "Installing jhbuild - autogen"
      shell: cd ~/checkout/jhbuild && ./autogen.sh

    - name: "Installing jhbuild - make"
      shell: cd ~/checkout/jhbuild && make 

    - name: "Installing jhbuild - make install"
      shell: cd ~/checkout/jhbuild && make install

    - name: "Creating glib schemas dir"
      file: path=~/install/share/glib-2.0/schemas state=directory mode=755

    - include: setup_default_ssh_key.yaml
