---
# vim:ff=unix ts=2 sw=2 ai expandtab
-
  hosts: dev_machine

  sudo: True

  vars_files:
    - "../default_variables.yaml"

  tasks:
    - name: "Creating /opt/gnome directory"
      file: path=/opt/gnome state=directory mode=777

    - name: "Updating apt-file cache"
      shell: apt-file update
