---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: "Installing jhbuild dependencies - this may take a very long time"
  shell: executable=/bin/bash echo -e "y\n" | ~/.local/bin/jhbuild sysdeps --install
  sudo: False

- name: "Installing auth key"
  template: src=../templates/.jhbuildrc-auth.j2 dest=~/.jhbuildrc-auth
  sudo: False

- name: "Cloning relevant modules - this will take a very long time - use htop and watch for git processes"
  shell: executable=/bin/bash ~/.local/bin/jhbuild update endless-apps
  sudo: False
