---
# vim:ff=unix ts=2 sw=2 ai expandtab

###
# Notice the minus on the line below -- this starts the playbook's record
# in the YAML document. Only one playbook is allowed per YAML file.  Indent
# the body of the playbook.
-
  hosts: dev_machine

  sudo: True

  vars_files:
    - "../default_variables.yaml"

  tasks:
    - include: setup_tools_root.yaml

    - include: create_eos_app_shortcuts.yaml

    - include: setup_dev_folder.yaml

    - include: setup_default_ssh_key.yaml

    - include: setup_jhbuild.yaml
