---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: "Ensuring that git is installed"
  apt: name=git update_cache=true cache_valid_time=259200

- name: "Creating checkout directory"
  file: path=~/checkout state=directory mode=755
  sudo: False

- name: "Cloning jhbuild"
  git: repo=git://git.gnome.org/jhbuild
       dest=~/checkout/jhbuild
  sudo: False

- name: "Installing jhbuild - autogen"
  shell: cd ~/checkout/jhbuild && ./autogen.sh
  sudo: False

- name: "Installing jhbuild - make"
  shell: cd ~/checkout/jhbuild && make 
  sudo: False

- name: "Installing jhbuild - make install"
  shell: cd ~/checkout/jhbuild && make install
  sudo: False

- name: "Creating glib schemas dir"
  file: path=~/install/share/glib-2.0/schemas state=directory mode=755
  sudo: False


- name: "Creating /opt/gnome directory"
  file: path=/opt/gnome state=directory mode=777

- name: "Updating apt-file cache"
  shell: apt-file update


- name: "Installing jhbuild dependencies - this may take a very long time"
  shell: executable=/bin/bash echo -e "y\n" | ~/.local/bin/jhbuild sysdeps --install
  sudo: False

- name: "Installing auth key"
  template: src=../templates/.jhbuildrc-auth.j2 dest=~/.jhbuildrc-auth
  sudo: False

- name: "Cloning relevant modules - this will take a very long time - use htop and watch for git processes"
  shell: executable=/bin/bash ~/.local/bin/jhbuild update endless-apps
  sudo: False
